"""Auto-generated from a live health-check of every helper source.
These sources consistently returned NO browsable content (dead upstreams,
broken parsers, cert/handshake failures, or a browser-only Cloudflare
challenge) on both /sources/popular and /sources/latest, so they are hidden
from the catalog. IDs match the engine's bare source id (no prefix).
570 disabled of 960 (390 working remain). Regenerate periodically."""

from __future__ import annotations

import concurrent.futures
import hashlib
import json
from collections.abc import Callable
from typing import TYPE_CHECKING

from nyora.config import config_file

if TYPE_CHECKING:
    from nyora.client import Nyora

def is_blocked_source(source_id: str, base_url: str | None = None) -> bool:
    """Return ``True`` if ``source_id`` should be hidden for the given server.

    Resolution: a per-server generated blocklist (cached after
    ``nyora blocklist refresh``) if present → otherwise the shipped static list.
    The static list is a sensible default for *any* server since every Nyora
    engine (your bundled one or a self-hosted server) runs the same parser
    stack, so the same upstreams are dead; run ``nyora blocklist refresh`` to
    tailor it.

    The engine returns prefixed ids (``parser:NAME``); the static set stores bare
    names, so the prefix is stripped before comparison.
    """
    bare = source_id.rsplit(":", 1)[-1]
    if base_url:
        cached = load_server_blocklist(base_url)
        if cached is not None:
            return source_id in cached or bare in cached
    return bare in BLOCKED_SOURCE_IDS


def _server_key(base_url: str | None) -> str:
    return hashlib.sha1((base_url or "").encode("utf-8")).hexdigest()[:12]


def blocklist_cache_file(base_url: str | None):
    """Path of the generated per-server blocklist cache (next to the config)."""
    return config_file().parent / f"blocked-{_server_key(base_url)}.json"


def load_server_blocklist(base_url: str | None) -> set[str] | None:
    """Return the generated blocklist for ``base_url``, or ``None`` if none exists."""
    path = blocklist_cache_file(base_url)
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        ids = data.get("blocked") if isinstance(data, dict) else data
        return set(ids) if isinstance(ids, list) else None
    except Exception:
        return None


def save_server_blocklist(base_url: str | None, blocked_ids) -> None:
    """Persist a generated blocklist for ``base_url``."""
    path = blocklist_cache_file(base_url)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps({"base_url": base_url, "blocked": sorted(blocked_ids)}, indent=1),
        encoding="utf-8",
    )


def generate_blocklist(
    client: Nyora,
    *,
    workers: int = 8,
    on_progress: Callable[[int, int, int], None] | None = None,
) -> set[str]:
    """Probe every catalog source on ``client``'s server and cache the dead ones.

    A source is "dead" if BOTH ``/sources/popular`` and ``/sources/latest`` return
    no entries. The result is saved via :func:`save_server_blocklist` for the
    client's base URL, so subsequent ``list()``/``catalog()`` calls hide them.

    This is exactly what makes the blocklist "auto-create after configuring a URL":
    run it once against your own server.
    """
    data = client.get("/sources/catalog")
    ids = [e.get("id") for e in (data.get("entries") or []) if e.get("id")]

    def probe(sid: str) -> tuple[str, bool]:
        for route in ("/sources/popular", "/sources/latest"):
            try:
                res = client.get(route, params={"id": sid, "page": 1})
                if res.get("entries"):
                    return sid, True
            except Exception:
                pass
        return sid, False

    dead: set[str] = set()
    total, done = len(ids), 0
    with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as ex:
        for sid, ok in ex.map(probe, ids):
            if not ok:
                dead.add(sid)
            done += 1
            if on_progress:
                on_progress(done, total, len(dead))
    save_server_blocklist(getattr(client, "base_url", None), dead)
    return dead


#: Bare source names hidden from ``list()`` / ``catalog()`` — dead or Cloudflare-walled.
BLOCKED_SOURCE_IDS: frozenset[str] = frozenset(
    (
    "ADONISFANSUB",
    "ADULT_WEBTOON",
    "ADUMANGA",
    "AINZSCANS",
    "ALLHENTAI",
    "ALLPORN_COMIC",
    "ALONESCANLATOR",
    "ALTERKAISCANS",
    "ALUCARDSCANS",
    "ANIMESAMA",
    "ANIMEXNOVEL",
    "APENASMAISUMYAOI",
    "APKOMIK",
    "ARABSHENTAI",
    "ARAREASCANS",
    "ARAZNOVEL",
    "ARCTICSCAN",
    "AREASCANS",
    "ARMONISCANS",
    "ARTHUR_SCAN",
    "ARVENSCANS",
    "ARYASCANS",
    "ASEMIFANSUB",
    "ASQORG",
    "ASTRASCANS",
    "ASURASCANSGG",
    "ASURASCANS_US",
    "ATEMPORAL",
    "ATHENAMANGA",
    "ATIKROST",
    "AYATOON",
    "AZORAMOON",
    "BABELWUXIA",
    "BANANA_MANGA",
    "BARMANGA",
    "BATCAVE",
    "BEEHENTAI",
    "BEETOON",
    "BEGATRANSLATION",
    "BERSERKSCAN",
    "BIRDTOON",
    "BLUELOCKSCAN",
    "BOKUGENTS",
    "BOOKMANGA",
    "BRMANGASTOP",
    "CAFECOMYAOI",
    "CMANGA",
    "COFFEE_MANGA",
    "COMICSVALLEY",
    "COMIX",
    "COMIZ",
    "COMX",
    "COSMIC_SCANS",
    "CRYSTALSCAN",
    "CVNSCAN",
    "CYPHERSCANS",
    "DAMCONUONG",
    "DARK_SCANS",
    "DAYCOMICS",
    "DEMONSECT",
    "DEMONSLAYERSCAN",
    "DESUME",
    "DEXHENTAI",
    "DIANXIATRADS",
    "DOCTRUYEN3Q",
    "DOUJINDESU",
    "DOUJINDESURIP",
    "DOUJINDESUUK",
    "DOUJINKU",
    "DOUJINSHELL",
    "DOUJIN_HENTAI_NET",
    "DRAGONMANGA",
    "DRAGONTEA",
    "DRAGONTRANSLATIONORG",
    "DREAMSCAN",
    "DRSTONE",
    "DTUPSCAN",
    "DUALEOTRUYEN",
    "EDOUJIN",
    "EDSCANLATION",
    "ELDERMANGA",
    "ELEVENSCANLATOR",
    "EMPERORSCAN",
    "ENRYUMANGA",
    "ERO18X",
    "EROSSCANS",
    "EVILMANGA",
    "FACTMANGA",
    "FAYSCANS",
    "FIREFORCE",
    "FIRESCANS",
    "FIRSTKISSMANHUA",
    "FLARES",
    "FMTEAM",
    "FREEMANGA",
    "FREEMANGATOP",
    "FURYMANGA",
    "FUTARI",
    "GAFELAND",
    "GEASSCOMICS",
    "GISTAMISHOUSEFANSUB",
    "GMANGA",
    "GOCTRUYENTRANH",
    "GOCTRUYENTRANHVUI",
    "GOLGEBAHCESI",
    "GOURMETSCANS",
    "GREEDSCANS",
    "GTOTHEGREATSITE",
    "GUNCEL_MANGA",
    "HADESNOFANSUB",
    "HAIKYUU",
    "HANGTRUYEN",
    "HARIMANGA",
    "HASTATEAM",
    "HASTATEAM_READER",
    "HAYALISTIC",
    "HELLSPARADISESCAN",
    "HENCHAN",
    "HENTAI18VN",
    "HENTAI3ZCC",
    "HENTAICUBE",
    "HENTAIMANGA",
    "HENTAIORIGINES",
    "HENTAIREAD",
    "HENTAISCANTRADVF",
    "HENTAITECA",
    "HENTAIVNBUZZ",
    "HENTAIVNSU",
    "HENTAIWEBTOON",
    "HENTAMAN",
    "HERENSCAN",
    "HHENTAIFR",
    "HIJALACOM",
    "HIKARISCAN",
    "HIPERCOOL",
    "HIPERDEX",
    "HITOMILA",
    "HNISCANTRAD",
    "HOIFANSUB",
    "HOTCOMICS",
    "HUNTERXHUNTERSCAN",
    "HWAGO",
    "ICHIROMANGA",
    "ILLUSIONSCAN",
    "IMPERIODABRITANNIA",
    "INOVASCANMANGA",
    "IRISSCANLATOR",
    "ITSYOURIGHTMANHUA",
    "JIANGZAITOON",
    "JIMANGA",
    "KABUSMANGA",
    "KAGANE",
    "KAISCANS",
    "KAKUSEIPROJECT",
    "KALANGO",
    "KATAKOMIK",
    "KINGDOMSCAN",
    "KINGS_MANGA",
    "KISSMANGA",
    "KLMANHUA",
    "KNIGHTNOSCANLATION",
    "KOHARU",
    "KOMIKCAST",
    "KOMIKDEWASA",
    "KOMIKGO",
    "KOMIKMAMA",
    "KOMIKREALM",
    "KOMIKSIN_CO",
    "KOMIKU",
    "KOMIKZOID",
    "KORELISCANS",
    "KUMAPAGE",
    "KUMASCANS",
    "KUNMANGA",
    "KURONEKO",
    "LAMIMANGA",
    "LANGGEEK",
    "LAVINIAFANSUB",
    "LECTORMANGA",
    "LEGENDSCANLATIONS",
    "LEITORDEMANGA",
    "LEKMANGACOM",
    "LEKMANGAORG",
    "LEPOYTL",
    "LERHENTAI",
    "LERMANGAS",
    "LERYAOI",
    "LICHMANGAS",
    "LILYUMFANSUB",
    "LIMBOSCAN",
    "LIMITEDTIMEPOJECT",
    "LUACOMIC_COM",
    "LUMOSKOMIK",
    "LUNAR_SCAN",
    "LUPITEAM",
    "LXMANGA",
    "MAFIAMANGA",
    "MAGERIN",
    "MAIDSECRET",
    "MANGA168",
    "MANGA18X",
    "MANGA1ST",
    "MANGAATREND",
    "MANGAAY",
    "MANGABALL_IS",
    "MANGABALL_KN",
    "MANGABALL_ML",
    "MANGABUDDY",
    "MANGABUFF",
    "MANGACIX",
    "MANGACLASH",
    "MANGACLOUD",
    "MANGACRAZY",
    "MANGACUTE",
    "MANGADEEMAK",
    "MANGADOP",
    "MANGAEFENDISI",
    "MANGAFASTNET",
    "MANGAFLAME",
    "MANGAFOREST",
    "MANGAFORFREE",
    "MANGAFOXFULL",
    "MANGAFR",
    "MANGAGEKO",
    "MANGAGEZGINI",
    "MANGAGOJO",
    "MANGAHAUS",
    "MANGAHENTAI",
    "MANGAHONA",
    "MANGAHUB_LINK",
    "MANGAITALIA",
    "MANGAJP",
    "MANGAKAKALOT",
    "MANGAKAKALOTTV",
    "MANGAKAWAII",
    "MANGAKAWAII_EN",
    "MANGAKINGS",
    "MANGAKISS",
    "MANGAKITA",
    "MANGAKOINU",
    "MANGAKOLEJI",
    "MANGAKOMA01",
    "MANGAKYO",
    "MANGALAND",
    "MANGALEK",
    "MANGALEKO",
    "MANGALEVELING",
    "MANGALINKNET",
    "MANGALIONZ",
    "MANGALIVRE",
    "MANGAMAMMY",
    "MANGAMANA",
    "MANGAMATE",
    "MANGAMUNDODRAMA",
    "MANGANINJA",
    "MANGAOKUTR",
    "MANGAONELOVE",
    "MANGAONI",
    "MANGAONLINE",
    "MANGAONLINETEAM",
    "MANGAONLINE_BLOG",
    "MANGAPUMA",
    "MANGARAW",
    "MANGAREADCO",
    "MANGAREADERTO",
    "MANGAROCK",
    "MANGAROCKTEAM",
    "MANGAROLLS",
    "MANGAROSE",
    "MANGASECT",
    "MANGASEHRI",
    "MANGASHIINA",
    "MANGASNOSEKAI",
    "MANGASOUL",
    "MANGASSCANS",
    "MANGASTARZ",
    "MANGASWAT",
    "MANGATERRA",
    "MANGATILKISI",
    "MANGATR",
    "MANGATXUNOFFICIAL",
    "MANGATX_GG",
    "MANGATYRANT",
    "MANGAWEEBS",
    "MANGAWT",
    "MANGAWT_NET",
    "MANGAXICO",
    "MANGAXYZ",
    "MANGAYARO",
    "MANGAZAVR",
    "MANGA_CRAB",
    "MANGA_DENIZI",
    "MANGA_DISTRICT",
    "MANGA_KOMI",
    "MANGA_MANHUA",
    "MANGA_SCANTRAD",
    "MANGA_WTF",
    "MANHASTRO",
    "MANHUABUG",
    "MANHUAES",
    "MANHUAFAST",
    "MANHUAGA",
    "MANHUAGOLD",
    "MANHUAMANHWA",
    "MANHUAUS",
    "MANHUAUSS",
    "MANHUAZONE",
    "MANHUAZONGHE",
    "MANHWA18ORG",
    "MANHWA68",
    "MANHWACLAN",
    "MANHWADESU",
    "MANHWAFREAKE",
    "MANHWAFULL",
    "MANHWAHENTAI",
    "MANHWAHENTAITO",
    "MANHWAINDO",
    "MANHWAKU",
    "MANHWALAND",
    "MANHWALAND_INK",
    "MANHWALATINO",
    "MANHWALIST",
    "MANHWAMANHUA",
    "MANHWAONLINE",
    "MANHWARAW",
    "MANHWARAW_COM",
    "MANHWASCO",
    "MANHWASMEN",
    "MANHWAS_ES",
    "MANHWAX",
    "MANHWA_ES",
    "MANJANOON",
    "MANTRAZSCAN",
    "MANYTOON",
    "MANYTOONME",
    "MANYTOON_CLUB",
    "MARMOTA",
    "MASHLESCAN",
    "MASTERKOMIK",
    "MEDIOCRETOONS",
    "MEDUSASCANS",
    "MEHENTAIVN",
    "MERLINSCANS",
    "MGKOMIK",
    "MI2MANGAES",
    "MIAUSCAN",
    "MIKOROKU",
    "MILFTOON",
    "MIMIHENTAI",
    "MINDAFANSUB",
    "MINITWOSCAN",
    "MINTMANGA",
    "MONZEEKOMIK",
    "MOONDAISY_SCANS",
    "MOONLOVERSSCAN",
    "MOONWITCHINLOVESCAN",
    "MRBENNE",
    "MUGIMANGA",
    "MUGIWARASOFICIAL",
    "MURIMSCAN",
    "MYHEROACADEMIASCAN",
    "MYREADINGMANGA",
    "MYSHOJO",
    "NEATMANGA",
    "NECROSCANS",
    "NETTRUYEN",
    "NETTRUYEN1975",
    "NETTRUYENFE",
    "NETTRUYENHE",
    "NETTRUYENLL",
    "NETTRUYENSSR",
    "NETTRUYENUU",
    "NETTRUYENVIE",
    "NEUMANGA",
    "NEWTRUYEN",
    "NGOMIK",
    "NHATTRUYENVN",
    "NHENTAI",
    "NHENTAI_TO",
    "NIGHTSCANS",
    "NIMEMOB",
    "NINEMANGA_BR",
    "NINEMANGA_DE",
    "NINEMANGA_EN",
    "NINEMANGA_ES",
    "NINEMANGA_FR",
    "NINEMANGA_IT",
    "NINEMANGA_RU",
    "NIRVANASCAN",
    "NITROMANGA",
    "NIVERAFANSUB",
    "NOCSUMMER",
    "NOINDEXSCAN",
    "NORTEROSE",
    "NOVELCROW",
    "NOVELMIC",
    "OLAOE",
    "OLIMPOSCANS",
    "ONEPIECESCAN",
    "ONEPUNCHMANSCAN",
    "OPIATOON",
    "OSHINOKO",
    "PANTHEONSCAN",
    "PASSAMAOSCAN",
    "PATIMANGA",
    "PERF_SCAN",
    "PHILIASCANS",
    "PHOENIXSCANS",
    "PIEDPIPERFANSUB",
    "PIEDPIPERFANSUBYY",
    "PIRULITOROSA",
    "PLATINUMSCANS",
    "PLUMACOMICS",
    "POINTZEROTOONS",
    "POJOKMANGA",
    "POPSMANGA",
    "PORNCOMIXONLINE",
    "PUSSYSUSSYTOONS",
    "RAGNARSCANS",
    "RAIJINSCANS",
    "RAIKISCAN",
    "RAINDROPTEAMFAN",
    "RAISCANS",
    "RAMAREADER",
    "RAWDEX",
    "RAYSSCAN",
    "READCOMICSONLINE",
    "READER_EVILFLOWERS",
    "READKOMIK",
    "REAPERSCANSUNORIGINAL",
    "REMANGA",
    "RESETSCANS",
    "REZOSCANS",
    "RIMUSCANS",
    "RIO2MANGANET",
    "ROMANTIKMANGA",
    "RUAHAPCHANHDAY",
    "RYZUKOMIK",
    "S2MANGA",
    "SADSCANS",
    "SAKAMOTODAYS",
    "SAMURAISCAN",
    "SAPPHIRESCAN",
    "SARCASMSCANS",
    "SCANBORUTO",
    "SCANHENTAIMENU",
    "SCANITA",
    "SCANJUJUTSUKAISEN",
    "SCANS4U",
    "SCANTRAD",
    "SCANVFORG",
    "SCYLLACOMICS",
    "SECTSCANS",
    "SEINEMANGA",
    "SEKAIKOMIK",
    "SEKTEKOMIK",
    "SELFMANGA",
    "SENKURO",
    "SETSUSCANS",
    "SHADOWMANGAS",
    "SHIBAMANGA",
    "SHIRAKAMI",
    "SHOOTINGSTARSCANS",
    "SILENCESCAN",
    "SIRENKOMIK",
    "SITEMANGA",
    "SNKSCAN",
    "SNOWMACHINETRANSLATION",
    "SOULSCANS",
    "SSREADING",
    "STELLARSABER",
    "SUMMANGA",
    "SUMMERTOON",
    "SUSHISCAN",
    "SUSSYSCAN",
    "SWEETSCAN",
    "TAROTSCANS",
    "TATAKAE_SCANS",
    "TAURUSMANGA",
    "TCBSCANSMANGA",
    "TECNOSCANS",
    "TEMAKIMANGAS",
    "TEMPESTFANSUBNET",
    "TEMPESTSCANS",
    "TENSHIMANGA",
    "TERRITORIOLEAL",
    "THEBLANK",
    "THUNDERSCANS",
    "TIMENAIGHT",
    "TITANMANGA",
    "TOKYOREVENGERS",
    "TOONFR",
    "TOONGOD",
    "TOONILY_ME",
    "TOONITUBE",
    "TOONIZY",
    "TOPCOMICPORNO",
    "TOPREADMANHWA",
    "TOPTRUYEN",
    "TRADUCCIONESAMISTOSAS",
    "TRADUCCIONESMOONLIGHT",
    "TRESDAOS",
    "TRUEMANGA",
    "TRUYENHENTAIVN",
    "TRUYENTRANH3Q",
    "TRUYENVN",
    "TUKANGKOMIK",
    "TUMANGAONLINE",
    "TUMANHWAS",
    "TUTTOANIMEMANGA",
    "TU_MANHWAS",
    "TYRANTSCANS",
    "ULASCOMIC",
    "USAGI",
    "UTOON",
    "UZAYMANGA",
    "VALKYRIESCAN",
    "VARNASCAN",
    "VCOMYCS",
    "VERCOMICSPORNO",
    "VERMANGASPORNO",
    "VINLANDSAGA",
    "WALPURGISCAN",
    "WAMANGA",
    "WAVETEAMY",
    "WEBDEXSCANS",
    "WEBTOONEMPIRE",
    "WEBTOONHATTI",
    "WEBTOONTR",
    "WEBTOONXYZ",
    "WEEBDEX_DE",
    "WEEBDEX_EN",
    "WEEBDEX_ES",
    "WEEBDEX_FR",
    "WEEBDEX_IT",
    "WEEBDEX_JA",
    "WEEBDEX_KO",
    "WEEBDEX_PT",
    "WEEBDEX_RU",
    "WEEBDEX_ZH",
    "WELOVEMANGA",
    "WESTMANGA",
    "WHALEMANGA",
    "WICKEDWITCHSCAN",
    "WINTERSCAN",
    "WITCHSCANS",
    "WONDERLANDSCAN",
    "WOOPREAD",
    "XCALIBRSCANS",
    "XSSCAN",
    "YANPFANSUB",
    "YAOIBAR",
    "YAOIFLIX",
    "YAOIHUB",
    "YAOIMANGAOKU",
    "YAOISCAN",
    "YAOIX3",
    "YCSCAN",
    "YOMUMANGAS",
    "YONABAR",
    "YUGENMANGAS",
    "YUMEKOMIK",
    "YURIGARDEN",
    "YURIGARDEN_R18",
    "YURILAB",
    "YURILIVE",
    "ZANDYNOFANSUB",
    "ZINCHANMANGA",
    "ZINCHANMANGA_NET",
    "ZIN_MANGA_COM",
    )
)
